fixing some path issues

diff --git a/infrastructure/cf-templates/formation.yaml b/infrastructure/cf-templates/formation.yaml
--- a/infrastructure/cf-templates/formation.yaml
+++ b/infrastructure/cf-templates/formation.yaml
@@ -10,7 +10,7 @@ Resources:
     CreationPolicy:
       ResourceSignal:
         Count: 1
-        Timeout: PT1200S
+        Timeout: PT600S
     Properties:
       LaunchConfigurationName: !Ref InstanceLaunchConfig
       TargetGroupARNs:
@@ -46,15 +46,16 @@ Resources:
         Fn::ImportValue:
           !Sub vpc-bc481fc5:craft-web-services-web-InstanceRoleProfile:name
       KeyName: flask-key-west2
-      ImageId: ami-7f43f307
+      ImageId: ami-b24222ca
       InstanceType: t2.micro
       SecurityGroups:
         - Fn::ImportValue:
             !Sub vpc-bc481fc5:craft-demo-base-app-WebServicesAppSg:id
+        - sg-28923956
       UserData:
         Fn::Base64: !Sub |
           #!/bin/bash
-
+          set -x
           # Temporarily override the default umask of 0077
           umask 0022
 
@@ -63,39 +64,47 @@ Resources:
 
           mkdir -p /tmp/deploy
           cd /tmp/deploy
-
-          ###### Download chef out of s3 ######s
-          # 496911069803-us-west-2-artifacts/chef/cookbooks.zip
-          aws s3 cp s3://${AWS::AccountId}-${AWS::Region}-artifacts/chef/cookbooks.zip ${AWS::StackName}.zip
-
-          if [ $? -ne 0 ]; then
-            # Unrecoverable error, so fail fast
-            cfn-signal --region ${AWS::Region} --resource AutoScalingGroup --stack ${AWS::StackName} --success false
-          fi
-
-          unzip -o ${AWS::StackName}.zip -d cookbooks
-
-          # ###### Run Chef ######
-          mkdir -p /var/log/chef
-
-          cd cookbooks
-          ls config/solo.rb
-          ls nodes/web-services/us-west-2/dev.json
-
-          chef-solo -c config/solo.rb -j nodes/web-services/us-west-2/dev.json -l debug --force-logger
-
-          if [ $? -eq 0 ]; then
-            # All done!
-            cfn-signal --region ${AWS::Region} --resource AutoScalingGroup --stack ${AWS::StackName}
+          ###### Local debugging support ######
+          #skip_gpg_and_boxset_download=true
+          if $skip_gpg_and_boxset_download;
+          then
+              # Return success
+              cfn-signal --region ${AWS::Region} --resource AutoScalingGroup --stack ${AWS::StackName}
           else
-            # Deploy failed upload logs and die
-            INSTANCE_ID=`curl http://169.254.169.254/latest/meta-data/instance-id`
-            curl -s http://169.254.169.254/latest/user-data > /var/log/user-data.log
-            # flask-west2-prod-west2-logs/fail_deploys/
-            for log in /var/log/chef/chef.log /var/log/userdata.log /var/log/boot.log /var/log/cloud-init-output.log /var/log/nginx/access.log /var/log/nginx/error.log; do
-              [ -f $log ] && aws s3 cp --acl bucket-owner-full-control $log s3://flask-west2-prod-west2-logs/fail_deploys/${AWS::StackName}/$INSTANCE_ID/`basename $log`
-            done
-            shutdown -h now
+            ###### Download chef out of s3 ######s
+            # 496911069803-us-west-2-artifacts/chef/cookbooks.zip
+            aws s3 cp s3://496911069803-us-west-2-artifacts/chef/cookbooks.zip ${AWS::StackName}.zip
+
+            if [ $? -ne 0 ]; then
+              # Unrecoverable error, so fail fast
+              cfn-signal --region ${AWS::Region} --resource AutoScalingGroup --stack ${AWS::StackName} --success false
+            fi
+
+            unzip -o ${AWS::StackName}.zip -d chef
+            cd chef
+
+            # ###### Run Chef ######
+            mkdir -p /var/log/chef
+
+            cd chef
+            ls config/solo.rb
+            ls nodes/web-services/us-west-2/dev.json
+
+            /usr/bin/chef-solo -c config/solo.rb -j nodes/web-services/us-west-2/dev.json -l debug --force-logger
+
+            if [ $? -eq 0 ]; then
+            #   # All done!
+              cfn-signal --region ${AWS::Region} --resource AutoScalingGroup --stack ${AWS::StackName}
+            else
+              # Deploy failed upload logs and die
+              INSTANCE_ID=`curl http://169.254.169.254/latest/meta-data/instance-id`
+              curl -s http://169.254.169.254/latest/user-data > /var/log/user-data.log
+              # flask-west2-prod-west2-logs/fail_deploys/
+              for log in /var/log/chef/chef.log /var/log/userdata.log /var/log/boot.log /var/log/cloud-*.log /var/log/nginx/access.log /var/log/nginx/error.log; do
+                [ -f $log ] && aws s3 cp --acl bucket-owner-full-control $log s3://flask-west2-prod-west2-logs/fail_deploys/${AWS::StackName}/$INSTANCE_ID/`basename $log`
+              done
+              shutdown -h now
+            fi
           fi
 
 Outputs:
